<a href="https://colab.research.google.com/github/Srinitha-netha/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy


In [ ]:
import numpy as np
import time

In [ ]:
a=[1,2,3,4,5,6,7,8,9,10]*1000
start=time.time()
for i in range(len(a)):
  a[i]=a[i]*2
print("Time taken:",time.time()-start)


Time taken: 0.0023925304412841797


In [ ]:
a=[1,2,3,4,5,6,7,8,9,10]*1000 # we use numpy to decrease the time complexity of an array and memory efficient

b=np.array(a)
start=time.time()
new_b=b*2
print("Time taken:",time.time()-start)


Time taken: 0.0002231597900390625


In [ ]:
import sys


In [ ]:
a=[1,2,3,4,5]
arr=np.array(a)
print("List size:",sys.getsizeof(a),"bytes")
print("Numpy size:",arr.nbytes,"bytes")

List size: 104 bytes
Numpy size: 40 bytes


In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
#dimensions and shape
arr=np.array(34)
arr.ndim

0

In [ ]:
b=np.array([1,2,3,1,2])
b.ndim

1

In [ ]:
a=np.array([[]]) # as long as the bracters increams the dimension also increases
a.ndim #1 bracket = 1 dimension
a.shape

(1, 0)

In [ ]:
b=np.array([[[]]])
b.ndim
b.shape

(1, 1, 0)

In [ ]:
ar=np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar=np.arange(0,10,2)
ar

array([0, 2, 4, 6, 8])

In [ ]:
arr=np.linspace(0,10,5) # start:stop :No of values between them
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
arr=np.logspace(1, 3, 3) #logarithmic scale array 10^1->10^3 -> with 3values
#start :stop:no of values between them
arr

array([  10.,  100., 1000.])

In [ ]:
arr1=np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros([3,2])
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
arr=np.ones([5,2],dtype=int) #by default it will be the float
arr

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
arr=np.full(10,2) #array full of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr=np.full([2,4],7) #[row,col],default value
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
arr=np.empty([2,3]) #unintialized array
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr=np.random.rand(10) #random array and range is from 0 to 1
arr

array([0.84692906, 0.58224043, 0.06303436, 0.00440406, 0.17491577,
       0.25872406, 0.09105919, 0.85067137, 0.38247986, 0.26356194])

In [ ]:
arr=np.random.rand(3,2)
arr

array([[0.28542374, 0.65298593],
       [0.7454895 , 0.36486611],
       [0.12211651, 0.77141288]])

In [ ]:
arr=np.random.randn(2,3) #random float values from std distribution
arr

array([[ 0.54910455, -1.25936038, -0.48868063],
       [ 0.4792703 ,  0.53081251, -0.08813602]])

In [ ]:
arr=np.random.randint(10,100,size=(2,3)) #start:stop ,size which means rows and col
arr

array([[96, 97, 12],
       [36, 55, 65]])

In [ ]:
#numpy datatypes and typeCasting
arr=np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr=np.array([1,2,3,4,5]) #only integers
arr.dtype

dtype('int64')

In [ ]:
arr=np.array([1.1,2,5,8,5])
arr.dtype

dtype('float64')

In [ ]:
arr=np.array(["1",2,3.5]) # here dtype('<U32') means it is a string
arr.dtype

dtype('<U32')

In [ ]:
#convert int to float
arr=np.array([1,2,3,4,5],dtype=float)
arr.dtype
#you can do even convert float to int also by change the values in array and dtype as int

dtype('float64')

In [ ]:
#type casting is -> astype()
arr=np.array([1,2,3])
arr1=arr.astype(float)
arr1

array([1., 2., 3.])

In [ ]:
#type Casting Error
#we cannot convert a str into a int or float

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize # each element takes 8 bytes of memory

8

In [ ]:
#REshape
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
reshaped2=reshaped.reshape(3,2)
reshaped2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#ravel->converts into 1D array
ravel=reshaped2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [ ]:
ravel[0]=100# it updates the values of 0 index
print(ravel)
print(reshaped2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [ ]:
#Flatten -> coverts into 1 D array
#it returns of copy of an array #Flatten is independent if any changes makes dodesnt reflect in original array
flat=reshaped2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [ ]:
flat[0]=100# it updates the values of 0 index
print(flat)
print(reshaped2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [ ]:
#Arithematic operations on Arrays
#there should be equal no of elements should be present in both arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)     #Addition
print(b-a)     #Subtraction
print(a*b)     #multiplication
print(a/b)     #division
print(a//b)    #Floor division
print(a%b)     #Remainder
print(a**2)    #Exponential

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[1 4 9]


#Universal Functions  -> Ufuncs



In [ ]:
#SquareRoot
arr=np.array([1,2,3,4])
arr1=np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.        ]
[1. 2. 3. 4.]


In [ ]:
#Exponential
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
#Sine
angles=[0,np.pi,np.pi/2]
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


#Indexing & Slicing


In [ ]:
a=np.array([1,2,3,4,5])
print(a[-1:-4:-1])
print(a[-1:-4])
print(a[: :2])
print(a[:])
print(a[0:]) #bydefault it will take stop value as last element
print(a[:6])  #bydefault it will take start value as first element
print(a[-1])
print(a[2])

[5 4 3]
[]
[1 3 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
5
3


In [ ]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix[0:2,0:3]) #for 0:2 for rows and 0:3 for cols
print(matrix[1: ,1:])

[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]


In [ ]:
#Index Array -> Advanced Indexing
#np.take() it is a built in fn to perform indexing and slicing
arr=np.array([10,20,30,40,50])
idx=[0,2]
print(np.take(arr,idx))

[10 30]


In [ ]:
#Iterating with nditer
arr=np.array([[1,2],[3,4],[1,5]])
for x in np.nditer(arr):
  print(x,end=" ")

1 2 3 4 1 5 

In [ ]:
#ndenumerator ->both index + value
for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 1
(2, 1) 5


#Views and Copies


In [ ]:
#view
arr=np.array([1,2,3,4,5])
view=arr[1:3]
view

array([2, 3])

In [ ]:
view[1]=10
view

array([ 2, 10])

In [ ]:
arr # the view changes is reflectiong to the original array

array([ 1,  2, 10,  4,  5])

In [ ]:
#copy
copy=arr[1:3].copy()
copy

array([ 2, 10])

In [ ]:
copy[0]=5     #by using the copy the changes made in copy doesnt reflecting into the original array
copy

array([ 5, 10])

In [ ]:
arr

array([ 1,  2, 10,  4,  5])

#Transpose of a matrix


In [ ]:
#transpose -> Interchanging the rows and cols
arr=np.array([[1,2],
              [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
arr.transpose()

array([[1, 3],
       [2, 4]])

In [ ]:
#swapaxes -> swap 2 specific axes in a matrix
arr=np.array([[[1,2],
              [3,4]]])
arr.shape

(1, 2, 2)

In [ ]:
swap=np.swapaxes(arr,0,1)
swap.shape


(2, 1, 2)

In [ ]:
#concatenation
a=np.array([1,2])
b=np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [ ]:
#vertical Stack
a=np.random.randint(10,100,size=(2,3))
b=np.random.randint(10,100,size=(2,3))
a


array([[65, 17, 16],
       [53, 54, 51]])

In [ ]:
b

array([[69, 72, 69],
       [66, 75, 39]])

In [ ]:
np.vstack((a,b))   #vstack with join array like ^|^ vertical

array([[65, 17, 16],
       [53, 54, 51],
       [69, 72, 69],
       [66, 75, 39]])

In [ ]:
a=np.random.randint(10,100,size=(2,3))
b=np.random.randint(10,100,size=(2,3))

In [ ]:
np.hstack((a,b)) #h stack with join array like <-->

array([[27, 32, 37, 70, 75, 32],
       [92, 54, 83, 80, 92, 19]])

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.stack((a,b),axis=1)           #axis 0 means row wise

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [ ]:
np.stack((a,b),axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#splitting the arrays
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.split(arr,2) # while splitting the array should be divided into 2 equal parts,e.g 3,that not divided into two equal parts it raises an error

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [ ]:
np.hsplit(arr,2)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [ ]:
np.vsplit(arr,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

#Repeating & Tileing



In [ ]:
arr=np.array([1,2,3]) #each element repeated twice
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
#Tile -> repeat the whole array
arr=np.array([1,2,3])
np.tile(arr,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

#Aggregate Functions

In [ ]:
arr=np.random.randint(10,20,size=(1,5))
print(arr)
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())
print(arr.var())

[[14 12 13 15 11]]
11
15
13.0
1.4142135623730951
2.0


In [ ]:
print(matrix)
print(np.sum(matrix,axis=0))
print(np.sum(matrix,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


#Cumulative Operations


In [ ]:
#cumulative operations ->  running total
arr=np.array([1,2,3])
print(np.cumsum(arr))
print(np.cumprod(arr))

[1 3 6]
[1 2 6]


In [ ]:
#where
result=np.where(arr<2,"low","high")
result

array(['low', 'high', 'high'], dtype='<U4')

In [ ]:
#arg where ->  return row columns position for 2d arrays
arr=np.array([10,25,30,50])
print(np.argwhere(arr>25))

[[2]
 [3]]


In [ ]:
mask=np.logical_and(arr>10,arr<50)
arr[mask]

array([25, 30])

In [ ]:
print(matrix)
print(np.argwhere(matrix>5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [ ]:
mask=np.logical_or(arr<5,arr<25)
arr[mask]

array([10])

In [ ]:
arr1=np.array([1,2,5,0,8,0,4,9,7,])
arr1

array([1, 2, 5, 0, 8, 0, 4, 9, 7])

In [ ]:
np.nonzero(arr1)

(array([0, 1, 2, 4, 6, 7, 8]),)

#Broadcasting


In [ ]:
#NUmpy ciompares the shapes of an array from the right to left
#Rules for Broadcasting
""" -> if shapes are equal they are compatible
-> if one is 1 it can be strectched to match other
-> if shapes are different and not 1 or equal -> X Error
"""

' -> if shapes are equal they are compatible\n-> if one is 1 it can be strectched to match other\n-> if shapes are different and not 1 or equal -> X Error\n'

In [ ]:
image=np.array([[200,150],[100,250]])
image

array([[200, 150],
       [100, 250]])

In [ ]:
brightness=image+50
brightness

array([[250, 200],
       [150, 300]])

In [ ]:
#Vectorization
#np.vectorize() -> Convert a regular function to be applied on the array
def square(x):
  return x*x
vfunc=np.vectorize(square)
print(arr)
print(vfunc(arr))

[10 25 30 50]
[ 100  625  900 2500]


In [ ]:
#Dealing with missing values
#np.nan -> not a number
arr=np.array([1,2,np.nan,5])
arr

array([ 1.,  2., nan,  5.])

In [ ]:
#np.inf and -np.inf which represents the poitive and negative infinte values
#np.isnan
#np.isinf
#np.isfinite
#these are functions  used to detect the any null values infinite and finite values
print(np.isnan(arr))

[False False  True False]


In [ ]:
b=np.array([1,2,np.nan,3,5,np.inf,8,10.2])
print(np.isinf(b))
print(np.isnan(b))
print(np.isfinite(b))
new_b=np.nan_to_num(b) #Remove  Nan/infinite values
print(new_b)

[False False False False False  True False False]
[False False  True False False False False False]
[ True  True False  True  True False  True  True]
[1.00000000e+000 2.00000000e+000 0.00000000e+000 3.00000000e+000
 5.00000000e+000 1.79769313e+308 8.00000000e+000 1.02000000e+001]
